Compatibilidad con Angular 9.1
platanus/ng2-rut pull request #27
Opened 2020-04-08 18:00 UTC by mbaeza

En el momento que se utiliza con Angular 9.1, el validador de RUT no funciona debido a que no encuntra la librería Render. Sugiere utilizar la Librería Render2

2020-06-09 19:51 UTC, tlarrain commented
Podrían mergear este PR y re compilar el paquete? gracias!

2020-06-09 22:07 UTC, llekn commented
@gmq

2020-08-26 02:41 UTC, skrosoft commented
Hello, alguien nos podría ayudar con esto? Se los agradecería un montón!
@gmq @llekn @blackjid @ldlsegovia @niesteszeck @vigohe @v-karbovnichy

2020-08-26 03:04 UTC, blackjid requested changes
No estoy ultra metido en angular, pero por lo que veo no basta con cambiar a `Renderer2`.
Adamas hay que cambiar las funciones que cambiaron en la nueva libreria.

me parece que solo es `setElementProperty` por `setProperty `
https://angular.io/guide/migration-renderer

2020-08-26 03:41 UTC, skrosoft commented
> No estoy ultra metido en angular, pero por lo que veo no basta con cambiar a `Renderer2`.
> Adamas hay que cambiar las funciones que cambiaron en la nueva libreria.
> 
> me parece que solo es `setElementProperty` por `setProperty `
> https://angular.io/guide/migration-renderer

Efectivamente, revise detalladamente la documentación que indicas y cada uno de los metodos migrados incluyendo `setElementProperty` por `setProperty` pero si te fijas bien, el proyecto ya ocupa `setElementProperty`

https://github.com/platanus/ng2-rut/pull/27/files#diff-cb4765738f57bd0649c56f800787441eR32

2020-08-26 12:23 UTC, blackjid commented
Yo diria que es al revés. El metodo `SetElementProperty` es de `Renderer` no de `Renderer2`...
![image](https://user-images.githubusercontent.com/228037/91302933-38e5de00-e775-11ea-86e4-a9a2e7ceac99.png)

2020-08-26 13:21 UTC, skrosoft commented
> Yo diria que es al revés. El metodo `SetElementProperty` es de `Renderer` no de `Renderer2`...
> ![image](https://user-images.githubusercontent.com/228037/91302933-38e5de00-e775-11ea-86e4-a9a2e7ceac99.png)

Tienes toda la razón, mis disculpas 😅 envié un PR ( @ #27 ) pero no se si alguien puede hacerle el Merge (?)

2020-08-27 18:26 UTC, blackjid commented
@skrosoft quería pedirte disculpas, pero no vamos a mergear el PR.

Lo que pasa es que nosotros ya no usamos esta librería, porque dejamos de usar angular.
No tiene mucho sentido que mantengamos una librería que no usamos, porque van a pasar estas cosas todo el rato.

Te invito a usar la libreria que hizo @danielsotopino  https://github.com/platanus/ng2-rut/issues/25#issuecomment-604518731
https://github.com/landscapedotcl/ng9-rut

Vamos a poner un mensaje de deprecated a esta librería para no generar mas confusion y expectativas.

2020-08-27 18:26 UTC, closed without merging

2020-08-27 18:29 UTC, skrosoft commented
@blackjid se entiende perfectamente, no te preocupes.
Muchas gracias por la recomendación y gracias por habernos informado